### ISSUE TITLE
Error: msg.startsWith is not a function on Guestbook page

### ISSUE THREAD

**Issue by christianavi** [leerob/leerob.io#636] opened 2023-07-13 08:49 UTC
So like I mentioned on the title, I get this error whenever I open the `guestbook/` page:
**Unhandled Runtime Error**
Error: msg.startsWith is not a function

Source
`console.error`
`node_modules\.pnpm\next@13.4.10-canary.6_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\esm\server\app-render\preload-component.js (5:0)`
```
app\guestbook\page.tsx (48:12) @ error

  46 |   }
  47 | } catch (error) {
> 48 |   console.error(error);
     |          ^
  49 | }
  50 | 
  51 | return (
```
  
This is what I see on the console:
```
  - error TypeError: msg.startsWith is not a function
    at GuestbookPage (./app/guestbook/page.tsx:52:17)
    at async Promise.all (index 0)
```
    
I am out of my depth here. I tried to find `msg.startsWith` on the whole project, but there were no results of it. What could this be?

**Comment by Nouhack** [comment] 2023-07-17 08:39
i had the same error , until someone told me : https://github.com/leerob/leerob.io/issues/634#issuecomment-1628298724

**Comment by z4nr34l** [comment] 2023-08-14 05:59
I've found a workaround some time ago.

(On latest next version) You need to install next-auth manual commit version `"next-auth": "0.0.0-manual.83c4ebd1"`, and add opentelemetry packages versions override according to package manager you are using to your `package.json`:

```json
"pnpm": {
    "overrides": {
      "@opentelemetry/api": "1.4.1",
      "@opentelemetry/core": "1.13.0",
      "@opentelemetry/exporter-trace-otlp-grpc": "0.39.1",
      "@opentelemetry/resources": "1.13.0",
      "@opentelemetry/sdk-trace-base": "1.13.0",
      "@opentelemetry/sdk-trace-node": "1.13.0",
      "@opentelemetry/semantic-conventions": "1.13.0"
    }
  },
```

After that make a clean install of packages and try again, in my projects it worked like a charm.

**Comment by z4nr34l** [comment] 2023-11-22 07:36
This error should not existst now, as I see that page was migrated out from contentlayer, so had I done in my repository, and cant reproduce this issue anymore.

@leerob could you close the issue as it is outdated?

**Comment by leerob** [comment] 2024-09-07 01:56
Moved to a different design: https://github.com/leerob/leerob.io/pull/727

**Closed by leerob** 2024-09-07 01:56 UTC
