### ISSUE TITLE
SWR fetching behavior 

### ISSUE THREAD

**Issue by omaralsoudanii** [leerob/leerob.io#367] opened 2021-09-09 14:33 UTC
@leerob 
I am not sure if this is a bug or related to the browser console being opened somehow, on page visit `/api/views/[slug]`  is triggered for every post (guess this is okay since the hook is used with each blog post in list view).

What is confusing is that if you click go to any article, the same requests (for the whole loaded list) are fired again, I can't confirm if this SWR gets refocused because the browser console or it actually fire all requests.

I changed with my code some SWR configs (binding to a key, get initial data etc..) and noticed that it kinda stopped requesting everything ‐ by kinda I mean it's random, also they return 304, is this from the API or SWR not actually calling the API by having stale time.

Check the below recording to see what I mean.

https://user-images.githubusercontent.com/7079173/132705213-d5959a83-cd6c-49cc-91d4-44539c133fec.mp4

**Comment by shuding** [comment] 2021-11-14 00:56
Hey, SWR author here! The recording seems broken and I can’t watch it. But from your description I guess it’s caused by re-focusing on the window when you click, where the focus was on the console.

**Comment by leerob** [comment] 2022-03-07 03:00
Closing this as it seems to be working as expected 🙏

**Closed by leerob** 2022-03-07 03:00 UTC
